version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Test123!
      MYSQL_DATABASE: dev_db
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: Test123!

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: